name: 自动更新比赛成绩

on:
  # 可以随时在 Actions 页面手动点击运行
  workflow_dispatch:

  # 每5分钟自动检查一次
  schedule:
    - cron: "*/5 * * * *"
      timezone: "Asia/Shanghai"

permissions:
  contents: write

jobs:
  update-scores:

    runs-on: ubuntu-latest

    steps:

      - name: 获取仓库
        uses: actions/checkout@v4


      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: 获取最新成绩并生成首页
        env:
          WOCZX_COOKIE: ${{ secrets.WOCZX_COOKIE }}
          WOCZX_AUTHORIZATION: ${{ secrets.WOCZX_AUTHORIZATION }}
        run: |
          python fetch_scores.py


      - name: 检查是否发生变化
        id: changes
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain README.md data/)" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "榜单发生变化"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "榜单没有变化"
          fi


      - name: 自动提交最新榜单
        if: steps.changes.outputs.changed == 'true'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md data/

          git commit -m "自动更新比赛成绩"

          git push